Write-Host "1. Seed the database:"
Write-Host "   py -3 seed.py"
Write-Host ""
Write-Host "2. Start fixed app in one terminal:"
Write-Host "   py -3 app.py"
Write-Host ""
Write-Host "3. Start vulnerable app in another terminal:"
Write-Host "   py -3 demo/vulnerable_app.py"
Write-Host ""
Write-Host "4. Demo URLs:"
Write-Host "   Fixed app:      http://127.0.0.1:5000"
Write-Host "   Vulnerable app: http://127.0.0.1:5001"
Write-Host "   CSRF vuln:      file:///$PWD/demo/csrf_attack_vulnerable.html"
Write-Host "   CSRF fixed:     file:///$PWD/demo/csrf_attack_fixed.html"
